# =============================================================================================
# Runde 35 Spur N "android" - Szenarien fuer den Pruefstand des ECHTEN Geraete-Entpackers (android_glue.c).
# Dossier: analysis/befunde_runde35/N_android.md. Aufruf (probes/r35_android.cmake):
#   cmake -DPRUEFSTAND=<exe> -DARBEIT=<ordner> -DTEIL=anzeige|konflikt -P test_r35_android_entpacker.cmake
#
# TEIL anzeige  (Punkt 1, Befund E2-1 "Fortschrittsanzeige auf sehr breiten Displays seitlich abgeschnitten"):
#   je Displaygroesse drei Laeufe - Uebergang v0.8.19 (laengster Titel "... EINMALIG GEPRUEFT", 44 Zeichen, dazu die
#   Fortschrittszeile), Dateifehler ("1 DATEIEN KONNTEN NICHT ENTPACKT WERDEN - SIEHE DEBUG.LOG", 57) und "alte Liste
#   nicht loeschbar" (58, der laengste Text des Entpackers). Verlangt: kein Text/Rechteck ausserhalb des Displays, keine
#   Ueberlappung, und der GANZE Text steht im Bild (auch umbrochen).
# TEIL konflikt (Punkt 2, Befund F-Y4/H8 "Datei <-> Ordner gleichen Namens im Update"): je Szenario Start 1 mit APK A,
#   Start 2 mit APK B (Update) - Start 2 muss im SELBEN Start fertig werden (SPIELSTART, Baum = B, Liste = B), Start 3
#   nimmt den schnellen Weg. Dazu zwei Listen, die das Geraet ablehnen muss (Ordner mit .neu-Endung, Datei+Ordner).
# =============================================================================================
cmake_minimum_required(VERSION 3.21)
if(NOT PRUEFSTAND OR NOT ARBEIT OR NOT TEIL)
    message(FATAL_ERROR "PRUEFSTAND, ARBEIT und TEIL setzen")
endif()
set(_FEHLER 0)
set(_AT "${ARBEIT}/${TEIL}")
file(REMOVE_RECURSE "${_AT}")
file(MAKE_DIRECTORY "${_AT}/logs")

macro(fehler text)
    message("   FEHLER: ${text}")
    math(EXPR _FEHLER "${_FEHLER} + 1")
endmacro()

function(datei pfad inhalt)
    get_filename_component(_d "${pfad}" DIRECTORY)
    file(MAKE_DIRECTORY "${_d}")
    file(WRITE "${pfad}" "${inhalt}")
endfunction()

# re15_assets.txt Format v2 aus shared_assets/ + synchro/ des APK-Ordners (wie build.gradle writeAssetManifest)
function(liste apk)
    file(GLOB_RECURSE _fs LIST_DIRECTORIES false RELATIVE "${apk}" "${apk}/shared_assets/*" "${apk}/synchro/*")
    list(SORT _fs)
    set(_z "")
    set(_n 0)
    set(_b 0)
    foreach(_f IN LISTS _fs)
        file(SIZE "${apk}/${_f}" _g)
        file(SHA256 "${apk}/${_f}" _h)
        string(APPEND _z "${_g}\t${_h}\t${_f}\n")
        math(EXPR _n "${_n} + 1")
        math(EXPR _b "${_b} + ${_g}")
    endforeach()
    file(WRITE "${apk}/re15_assets.txt" "# re15 assets v2 ${_n} ${_b}\n${_z}")
endfunction()

# Ein Start des Entpackers. Setzt LAUF_TEXT (stderr) im Aufrufer.
function(lauf titel root apk w h soll_rc)
    set(_log "${_AT}/logs/${titel}.txt")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env "H_ROOT=${root}" "H_APK=${apk}" "H_W=${w}" "H_H=${h}" "${PRUEFSTAND}"
                    RESULT_VARIABLE _rc OUTPUT_FILE "${_log}.stdout" ERROR_FILE "${_log}" TIMEOUT 60)
    file(READ "${_log}" _t)
    set(LAUF_TEXT "${_t}" PARENT_SCOPE)
    message("== ${titel} (${w}x${h}): EXIT=${_rc} (soll ${soll_rc})")
    string(REGEX MATCHALL "[^\n]*(Abgleich|Entpacken fertig|Assets aktuell|ABBRUCH|FEHLER|Konflikt|entfernt|WARNUNG|PRUEFSTAND-AUSSERHALB|PRUEFSTAND-UEBERLAPPUNG|SPIELSTART|nicht anlegbar|rename)[^\n]*" _z "${_t}")
    foreach(_l IN LISTS _z)
        string(SUBSTRING "${_l}" 0 220 _l)
        message("     ${_l}")
    endforeach()
    if(NOT "${_rc}" STREQUAL "${soll_rc}")
        fehler("${titel}: EXIT=${_rc}, soll ${soll_rc}")
    endif()
    set(_FEHLER ${_FEHLER} PARENT_SCOPE)
endfunction()

function(muss_enthalten titel text muster)
    string(FIND "${text}" "${muster}" _i)
    if(_i LESS 0)
        fehler("${titel}: '${muster}' fehlt in der Ausgabe")
    endif()
    set(_FEHLER ${_FEHLER} PARENT_SCOPE)
endfunction()

function(darf_nicht_enthalten titel text muster)
    string(REGEX MATCH "${muster}" _m "${text}")
    if(_m)
        fehler("${titel}: verboten '${_m}'")
    endif()
    set(_FEHLER ${_FEHLER} PARENT_SCOPE)
endfunction()

# Speicherordner == APK: jede gelistete Datei bytegleich, keine zusaetzliche Datei, kein Ordner, der keine gelistete
# Datei traegt, und "zuletzt entpackt" == Liste der APK.
function(baum_gleich titel root apk)
    file(GLOB_RECURSE _soll LIST_DIRECTORIES false RELATIVE "${apk}" "${apk}/shared_assets/*" "${apk}/synchro/*")
    foreach(_f IN LISTS _soll)
        if(IS_DIRECTORY "${root}/${_f}" OR NOT EXISTS "${root}/${_f}")
            fehler("${titel}: ${_f} fehlt im Speicher (oder ist ein Ordner)")
            continue()
        endif()
        file(SHA256 "${apk}/${_f}" _a)
        file(SHA256 "${root}/${_f}" _b)
        if(NOT _a STREQUAL _b)
            fehler("${titel}: ${_f} hat anderen Inhalt als die APK")
        endif()
    endforeach()
    file(GLOB_RECURSE _ist LIST_DIRECTORIES true RELATIVE "${root}" "${root}/shared_assets/*" "${root}/synchro/*")
    foreach(_f IN LISTS _ist)
        if(IS_DIRECTORY "${root}/${_f}")
            set(_traegt FALSE)
            foreach(_s IN LISTS _soll)
                string(FIND "${_s}" "${_f}/" _i)
                if(_i EQUAL 0)
                    set(_traegt TRUE)
                    break()
                endif()
            endforeach()
            if(NOT _traegt)
                fehler("${titel}: Ordner ${_f}/ im Speicher traegt keine gelistete Datei")
            endif()
        else()
            list(FIND _soll "${_f}" _i)
            if(_i LESS 0)
                fehler("${titel}: zusaetzliche Datei im Speicher: ${_f}")
            endif()
        endif()
    endforeach()
    if(NOT EXISTS "${root}/re15_assets_entpackt.txt")
        fehler("${titel}: re15_assets_entpackt.txt fehlt (Lauf nicht fertig)")
    else()
        file(SHA256 "${apk}/re15_assets.txt" _a)
        file(SHA256 "${root}/re15_assets_entpackt.txt" _b)
        if(NOT _a STREQUAL _b)
            fehler("${titel}: re15_assets_entpackt.txt != Liste der APK")
        endif()
    endif()
    set(_FEHLER ${_FEHLER} PARENT_SCOPE)
endfunction()

function(grundstock apk)          # zwei Dateien, die in jedem Szenario bleiben
    datei("${apk}/shared_assets/PSX/a.bin" "AAAA")
    datei("${apk}/synchro/STAGE1/m.wav" "mmmm")
endfunction()

# =============================================================================================
if(TEIL STREQUAL "anzeige")
    set(_A "${_AT}/apk")
    grundstock("${_A}")
    datei("${_A}/shared_assets/PSX/DATA/b.bin" "bbbb")
    liste("${_A}")
    set(_F "${_AT}/apk_fehler")      # Liste nennt eine Datei, die in der APK fehlt -> Dateifehler
    grundstock("${_F}")
    datei("${_F}/shared_assets/PSX/weg.bin" "wwww")
    liste("${_F}")
    file(REMOVE "${_F}/shared_assets/PSX/weg.bin")

    set(_TITEL_U "RE1.5 PORT - ASSETS WERDEN EINMALIG GEPRUEFT")
    set(_TEXT_D "1 DATEIEN KONNTEN NICHT ENTPACKT WERDEN - SIEHE DEBUG.LOG")
    set(_TEXT_L "FEHLER: ALTE ASSET-LISTE NICHT LOESCHBAR - SIEHE DEBUG.LOG")
    # 2400x1080 = gemessenes Geraet (Runde 34a, E2-1); 1920x1080/1280x720 16:9; 2560x1080 21:9; 3200x1440 20:9 QHD;
    # 3840x1080 und 5120x1440 32:9; 800x480 kleines Querformat; 1080x2400 hochkant; 320x240 PSX-Format; 160x120 Notfall
    foreach(_g 2400x1080 1920x1080 1280x720 2560x1080 3200x1440 3840x1080 5120x1440 800x480 1080x2400 320x240 160x120)
        string(REPLACE "x" ";" _wh "${_g}")
        list(GET _wh 0 _w)
        list(GET _wh 1 _h)
        # a) Uebergang v0.8.19: alter Marker liegt da -> Titel "... EINMALIG GEPRUEFT" + Fortschrittszeile
        set(_R "${_AT}/s_u_${_g}")
        datei("${_R}/re15_assets_ok.txt" "1")
        lauf("A_${_g}_uebergang" "${_R}" "${_A}" ${_w} ${_h} 0)
        muss_enthalten("A_${_g}_uebergang" "${LAUF_TEXT}" "text='${_TITEL_U} ")
        muss_enthalten("A_${_g}_uebergang" "${LAUF_TEXT}" "3 / 3 DATEIEN")
        darf_nicht_enthalten("A_${_g}_uebergang" "${LAUF_TEXT}" "PRUEFSTAND-AUSSERHALB[^\n]*|PRUEFSTAND-UEBERLAPPUNG[^\n]*")
        # b) Dateifehler -> fehler_halten mit dem 57-Zeichen-Text
        set(_R "${_AT}/s_f_${_g}")
        file(MAKE_DIRECTORY "${_R}")
        lauf("A_${_g}_dateifehler" "${_R}" "${_F}" ${_w} ${_h} 1)
        muss_enthalten("A_${_g}_dateifehler" "${LAUF_TEXT}" "text='RE1.5 PORT - FEHLER ${_TEXT_D}'")
        darf_nicht_enthalten("A_${_g}_dateifehler" "${LAUF_TEXT}" "PRUEFSTAND-AUSSERHALB[^\n]*|PRUEFSTAND-UEBERLAPPUNG[^\n]*")
        # c) "zuletzt entpackt" ist ein Ordner -> unlink scheitert (nicht ENOENT) -> der 58-Zeichen-Text
        set(_R "${_AT}/s_l_${_g}")
        datei("${_R}/re15_assets_entpackt.txt/x" "x")
        lauf("A_${_g}_liste" "${_R}" "${_A}" ${_w} ${_h} 1)
        muss_enthalten("A_${_g}_liste" "${LAUF_TEXT}" "text='RE1.5 PORT - FEHLER ${_TEXT_L}'")
        darf_nicht_enthalten("A_${_g}_liste" "${LAUF_TEXT}" "PRUEFSTAND-AUSSERHALB[^\n]*|PRUEFSTAND-UEBERLAPPUNG[^\n]*")
    endforeach()

# =============================================================================================
elseif(TEIL STREQUAL "konflikt")
    # Szenario: A frisch, Vorbereitung im Speicher (optional), B als Update im SELBEN Start, B noch einmal (schneller Weg)
    function(szenario name a b vorbereitung konflikt_soll)
        set(_R "${_AT}/s_${name}")
        file(MAKE_DIRECTORY "${_R}")
        lauf("${name}_1_frisch" "${_R}" "${a}" 1280 720 0)
        baum_gleich("${name}_1_frisch" "${_R}" "${a}")
        if(vorbereitung)
            foreach(_v IN LISTS vorbereitung)
                datei("${_R}/${_v}" "verwaist")
            endforeach()
        endif()
        lauf("${name}_2_update" "${_R}" "${b}" 1280 720 0)
        muss_enthalten("${name}_2_update" "${LAUF_TEXT}" "PRUEFSTAND: SPIELSTART")
        if(konflikt_soll)
            muss_enthalten("${name}_2_update" "${LAUF_TEXT}" "${konflikt_soll}")
        endif()
        baum_gleich("${name}_2_update" "${_R}" "${b}")
        lauf("${name}_3_neustart" "${_R}" "${b}" 1280 720 0)
        muss_enthalten("${name}_3_neustart" "${LAUF_TEXT}" "Assets aktuell (schneller Weg)")
        set(_FEHLER ${_FEHLER} PARENT_SCOPE)
    endfunction()

    # K1 = Befund H8: Ordner PSX/q/ (mit c) wird Datei PSX/q
    grundstock("${_AT}/K1_A")
    datei("${_AT}/K1_A/shared_assets/PSX/q/c" "cccc")
    liste("${_AT}/K1_A")
    grundstock("${_AT}/K1_B")
    datei("${_AT}/K1_B/shared_assets/PSX/q" "qqqqq")
    liste("${_AT}/K1_B")
    szenario(K1_ordner_wird_datei "${_AT}/K1_A" "${_AT}/K1_B" "" "")

    # K2 = Befund H7 (umgekehrt): Datei PSX/q wird Ordner PSX/q/ (mit c)
    szenario(K2_datei_wird_ordner "${_AT}/K1_B" "${_AT}/K1_A" "" "")

    # K3 = Befund F-Y4 am Geraet: ein (verwaister) ORDNER auf dem Namen der Zwischendatei PSX/X.neu, X wird geaendert
    grundstock("${_AT}/K3_A")
    datei("${_AT}/K3_A/shared_assets/PSX/X" "xxxx1")
    liste("${_AT}/K3_A")
    grundstock("${_AT}/K3_B")
    datei("${_AT}/K3_B/shared_assets/PSX/X" "xxxx2")
    liste("${_AT}/K3_B")
    szenario(K3_ordner_auf_zwischendatei "${_AT}/K3_A" "${_AT}/K3_B" "shared_assets/PSX/X.neu/rest" "Konflikt geraeumt")

    # K4: eine (verwaiste) DATEI auf dem Namen eines Ordners, den das Update braucht
    grundstock("${_AT}/K4_A")
    liste("${_AT}/K4_A")
    grundstock("${_AT}/K4_B")
    datei("${_AT}/K4_B/shared_assets/PSX/q/c" "cccc")
    liste("${_AT}/K4_B")
    szenario(K4_datei_auf_ordnername "${_AT}/K4_A" "${_AT}/K4_B" "shared_assets/PSX/q" "Konflikt geraeumt")

    # K5: ein (verwaister) ORDNER mit Unterordnern auf dem Namen einer Datei, die das Update bringt
    szenario(K5_ordner_auf_dateiname "${_AT}/K4_A" "${_AT}/K1_B" "shared_assets/PSX/q/x/y/rest;shared_assets/PSX/q/z" "Konflikt geraeumt")

    # K6: wie H8, aber nur in Gross/klein verschieden (App-Speicher und NTFS sind case-insensitiv)
    grundstock("${_AT}/K6_A")
    datei("${_AT}/K6_A/shared_assets/PSX/Q/c" "cccc")
    liste("${_AT}/K6_A")
    szenario(K6_gross_klein "${_AT}/K6_A" "${_AT}/K1_B" "" "")

    # L1/L2: Listen, die das Geraet ABLEHNEN muss (fail closed, nichts entpackt) - sonst waere das Raeumen nicht sicher
    set(_MS "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
    datei("${_AT}/L1/re15_assets.txt" "# re15 assets v2 2 9\n4\t${_MS}\tshared_assets/PSX/X\n5\t${_MS}\tshared_assets/PSX/X.neu/B\n")
    file(MAKE_DIRECTORY "${_AT}/s_L1")
    lauf(L1_ordner_mit_neu_endung "${_AT}/s_L1" "${_AT}/L1" 1280 720 1)
    muss_enthalten(L1 "${LAUF_TEXT}" "unzulaessiger Pfad")
    datei("${_AT}/L2/re15_assets.txt" "# re15 assets v2 2 9\n4\t${_MS}\tshared_assets/PSX/q\n5\t${_MS}\tshared_assets/psx/Q/c\n")
    file(MAKE_DIRECTORY "${_AT}/s_L2")
    lauf(L2_datei_und_ordner_gleich "${_AT}/s_L2" "${_AT}/L2" 1280 720 1)
    muss_enthalten(L2 "${LAUF_TEXT}" "Datei und Ordner gleichen Namens")
    foreach(_s s_L1 s_L2)
        if(EXISTS "${_AT}/${_s}/shared_assets")
            fehler("${_s}: trotz ungueltiger Liste wurde entpackt")
        endif()
    endforeach()
else()
    message(FATAL_ERROR "TEIL unbekannt: ${TEIL}")
endif()

if(_FEHLER GREATER 0)
    message(FATAL_ERROR "${_FEHLER} Fehler (Protokolle: ${_AT}/logs)")
endif()
message("== ${TEIL}: alle Szenarien bestanden")
