/* GENERATED by scripts/door_graph.py — per-room ENTRY spawn taken from an
 * inbound door (a door in another room whose destination is this room), so
 * the PC room-browser drops the player at a walkable, correct-band spot.
 * PARALLEL to re15_room_ids[] in re15_room_list.h (same sorted room order).
 * {x,y,z,yaw,cut}; all-zero = no inbound door found (browser falls back). */
#ifndef RE15_ROOM_SPAWNS_H
#define RE15_ROOM_SPAWNS_H
typedef struct { short x, y, z, yaw; unsigned char cut; } re15_room_spawn_t;
static const re15_room_spawn_t re15_room_spawns[] = {
    { 8850, 0, -3150, 0, 0 },  /* ROOM1000 (FLR-floor) */
    { 8850, 0, -3150, 0, 0 },  /* ROOM1001 (FLR-floor) */
    { 3650, 0, -3950, 2048, 4 },  /* ROOM1010 (inbound-door) */
    { 3650, 0, -3950, 2048, 4 },  /* ROOM1011 (inbound-door) */
    { -4000, 0, -18000, 2695, 11 },  /* ROOM1020 (inbound-door) */
    { -4000, 0, -18000, 2695, 11 },  /* ROOM1021 (inbound-door) */
    { -8200, 0, -22500, 1024, 6 },  /* ROOM1030 (inbound-door) */
    { -8200, 0, -22500, 1024, 6 },  /* ROOM1031 (inbound-door) */
    { -24000, 0, 16500, 2048, 6 },  /* ROOM1040 (inbound-door) */
    { -24000, 0, 16500, 2048, 6 },  /* ROOM1041 (inbound-door) */
    { 14700, 0, -13500, 0, 4 },  /* ROOM1050 (inbound-door) */
    { 14700, 0, -13500, 0, 4 },  /* ROOM1051 (inbound-door) */
    { 26000, 0, 25300, 2048, 7 },  /* ROOM1060 (inbound-door) */
    { 26000, 0, 25300, 2048, 7 },  /* ROOM1061 (inbound-door) */
    { 160, 0, 6145, 0, 0 },  /* ROOM1070 (inbound-door) */
    { 160, 0, 6145, 0, 0 },  /* ROOM1071 (inbound-door) */
    { -13650, 0, -900, 1024, 0 },  /* ROOM1080 (inbound-door) */
    { -13650, 0, -900, 1024, 0 },  /* ROOM1081 (inbound-door) */
    { -10100, -1800, 4200, 3072, 3 },  /* ROOM1090 (inbound-door) */
    { -10100, -1800, 4200, 3072, 3 },  /* ROOM1091 (inbound-door) */
    { 26200, -14400, 24800, 2048, 0 },  /* ROOM10A0 (inbound-door) */
    { 26200, -14400, 24800, 2048, 0 },  /* ROOM10A1 (inbound-door) */
    { 16490, -9000, -8110, 544, 0 },  /* ROOM10B0 (inbound-door) */
    { 16490, -9000, -8110, 544, 0 },  /* ROOM10B1 (inbound-door) */
    { 300, 0, 9550, 0, 0 },  /* ROOM10C0 (inbound-door) */
    { 300, 0, 9550, 0, 0 },  /* ROOM10C1 (inbound-door) */
    { 7650, 0, 11400, 2048, 3 },  /* ROOM10D0 (inbound-door) */
    { 7650, 0, 11400, 2048, 3 },  /* ROOM10D1 (inbound-door) */
    { -8050, 0, 3200, 1024, 0 },  /* ROOM10E0 (inbound-door) */
    { -8050, 0, 3200, 1024, 0 },  /* ROOM10E1 (inbound-door) */
    { 8400, 0, -350, 2048, 0 },  /* ROOM10F0 (inbound-door) */
    { 8400, 0, -350, 2048, 0 },  /* ROOM10F1 (inbound-door) */
    { -20900, 0, -10336, 1024, 5 },  /* ROOM1100 (inbound-door) */
    { -20900, 0, -10336, 1024, 5 },  /* ROOM1101 (inbound-door) */
    { -2400, 0, -5000, 0, 0 },  /* ROOM1110 (inbound-door) */
    { -2400, 0, -5000, 0, 0 },  /* ROOM1111 (inbound-door) */
    { 150, 0, 9550, 0, 0 },  /* ROOM1120 (inbound-door) */
    { 150, 0, 9550, 0, 0 },  /* ROOM1121 (inbound-door) */
    { -2200, 0, -2150, 0, 2 },  /* ROOM1130 (inbound-door) */
    { -2200, 0, -2150, 0, 2 },  /* ROOM1131 (inbound-door) */
    { -7600, 0, -17600, 0, 0 },  /* ROOM1140 (inbound-door) */
    { -7600, 0, -17600, 0, 0 },  /* ROOM1141 (inbound-door) */
    { -17150, 0, -11960, 1600, 0 },  /* ROOM1150 (inbound-door) */
    { -17150, 0, -11960, 1600, 0 },  /* ROOM1151 (inbound-door) */
    { -300, 0, -17400, 1024, 0 },  /* ROOM1160 (inbound-door) */
    { -300, 0, -17400, 1024, 0 },  /* ROOM1161 (inbound-door) */
    { 4014, -7200, -7436, 3072, 3 },  /* ROOM1170 (inbound-door) */
    { 4014, -7200, -7436, 3072, 3 },  /* ROOM1171 (inbound-door) */
    { -358, 0, -6536, 3072, 2 },  /* ROOM1180 (inbound-door) */
    { -358, 0, -6536, 3072, 2 },  /* ROOM1181 (inbound-door) */
    { 3174, 0, -11182, 1024, 0 },  /* ROOM1190 (inbound-door) */
    { 3174, 0, -11182, 1024, 0 },  /* ROOM1191 (inbound-door) */
    { 7500, -5400, 10650, 1024, 10 },  /* ROOM11A0 (inbound-door) */
    { 7500, -5400, 10650, 1024, 10 },  /* ROOM11A1 (inbound-door) */
    { -26483, 0, -18094, 0, 0 },  /* ROOM11B0 (inbound-door) */
    { -26483, 0, -18094, 0, 0 },  /* ROOM11B1 (inbound-door) */
    { -25279, 0, 17268, 4603, 0 },  /* ROOM11C0 (inbound-door) */
    { -25279, 0, 17268, 4603, 0 },  /* ROOM11C1 (inbound-door) */
    { -300, 0, -17400, 1024, 0 },  /* ROOM11D0 (inbound-door) */
    { -300, 0, -17400, 1024, 0 },  /* ROOM11D1 (inbound-door) */
    { 5112, 0, -5348, 3072, 2 },  /* ROOM11E0 (inbound-door) */
    { 5112, 0, -5348, 3072, 2 },  /* ROOM11E1 (inbound-door) */
    { 250, 0, 250, 1024, 0 },  /* ROOM11F0 (inbound-door) */
    { 250, 0, 250, 1024, 0 },  /* ROOM11F1 (inbound-door) */
    { -20154, 0, -25245, 3040, 0 },  /* ROOM1200 (inbound-door) */
    { -20154, 0, -25245, 3040, 0 },  /* ROOM1201 (inbound-door) */
    { -26400, 0, -2200, 0, 0 },  /* ROOM1210 (inbound-door) */
    { -26400, 0, -2200, 0, 0 },  /* ROOM1211 (inbound-door) */
    { -22400, 0, -6500, 2048, 0 },  /* ROOM1220 (inbound-door) */
    { -22400, 0, -6500, 2048, 0 },  /* ROOM1221 (inbound-door) */
    { -358, 0, -6536, 3072, 2 },  /* ROOM1230 (inbound-door) */
    { -358, 0, -6536, 3072, 2 },  /* ROOM1231 (inbound-door) */
    { -26214, 0, -3861, 0, 0 },  /* ROOM1240 (inbound-door) */
    { -26214, 0, -3861, 0, 0 },  /* ROOM1241 (inbound-door) */
    { -3100, 0, -7800, 0, 0 },  /* ROOM1250 (FLR-floor) */
    { -3100, 0, -7800, 0, 0 },  /* ROOM1251 (FLR-floor) */
    { -20250, -1800, -6700, 1024, 15 },  /* ROOM1260 (inbound-door) */
    { -20250, -1800, -6700, 1024, 15 },  /* ROOM1261 (inbound-door) */
    { 0, 0, 0, 0, 0 },  /* ROOM1270 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM1271 (no inbound door, no FLR) */
    { -12635, 0, -2905, 0, 0 },  /* ROOM2000 (FLR-floor) */
    { -12635, 0, -2905, 0, 0 },  /* ROOM2001 (FLR-floor) */
    { -4600, 0, -4950, 0, 0 },  /* ROOM2010 (inbound-door) */
    { -4600, 0, -4950, 0, 0 },  /* ROOM2011 (inbound-door) */
    { -14200, -1800, 2450, 1024, 5 },  /* ROOM2020 (inbound-door) */
    { -14200, -1800, 2450, 1024, 5 },  /* ROOM2021 (inbound-door) */
    { -450, -16200, -9700, 3072, 13 },  /* ROOM2030 (inbound-door) */
    { -450, -16200, -9700, 3072, 13 },  /* ROOM2031 (inbound-door) */
    { -3900, -9000, -19850, 2048, 11 },  /* ROOM2040 (inbound-door) */
    { -3900, -9000, -19850, 2048, 11 },  /* ROOM2041 (inbound-door) */
    { 9100, -5400, 4100, 1024, 0 },  /* ROOM2050 (inbound-door) */
    { 9100, -5400, 4100, 1024, 0 },  /* ROOM2051 (inbound-door) */
    { 7600, 0, 3950, 2048, 0 },  /* ROOM2060 (inbound-door) */
    { 7600, 0, 3950, 2048, 0 },  /* ROOM2061 (inbound-door) */
    { -18650, 0, -19300, 0, 12 },  /* ROOM2070 (inbound-door) */
    { -18650, 0, -19300, 0, 12 },  /* ROOM2071 (inbound-door) */
    { -23200, -9000, -16700, 0, 0 },  /* ROOM2080 (inbound-door) */
    { -23200, -9000, -16700, 0, 0 },  /* ROOM2081 (inbound-door) */
    { -8200, 0, -25550, 0, 0 },  /* ROOM2090 (inbound-door) */
    { -8200, 0, -25550, 0, 0 },  /* ROOM2091 (inbound-door) */
    { 25800, -3600, -800, 1024, 8 },  /* ROOM20A0 (inbound-door) */
    { 25800, -3600, -800, 1024, 8 },  /* ROOM20A1 (inbound-door) */
    { -12635, 0, -2905, 0, 0 },  /* ROOM20B0 (FLR-floor) */
    { -12635, 0, -2905, 0, 0 },  /* ROOM20B1 (FLR-floor) */
    { 0, 0, 0, 0, 0 },  /* ROOM20C0 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM20C1 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM20D0 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM20D1 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM20E0 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM20E1 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM20F0 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM20F1 (no inbound door, no FLR) */
    { -13400, 0, -16900, 0, 0 },  /* ROOM3000 (FLR-floor) */
    { -13400, 0, -16900, 0, 0 },  /* ROOM3001 (FLR-floor) */
    { -23168, 0, 11769, 4192, 1 },  /* ROOM3010 (inbound-door) */
    { -23168, 0, 11769, 4192, 1 },  /* ROOM3011 (inbound-door) */
    { -26300, 0, -22550, 0, 7 },  /* ROOM3020 (inbound-door) */
    { -26300, 0, -22550, 0, 7 },  /* ROOM3021 (inbound-door) */
    { -25323, 0, -25886, -1056, 1 },  /* ROOM3030 (inbound-door) */
    { -25323, 0, -25886, -1056, 1 },  /* ROOM3031 (inbound-door) */
    { -26350, 0, -5100, 0, 1 },  /* ROOM3040 (inbound-door) */
    { -26350, 0, -5100, 0, 1 },  /* ROOM3041 (inbound-door) */
    { -23996, 0, 1523, 1024, 0 },  /* ROOM3050 (inbound-door) */
    { -23996, 0, 1523, 1024, 0 },  /* ROOM3051 (inbound-door) */
    { -26027, 0, -22532, 4112, 0 },  /* ROOM3060 (inbound-door) */
    { -26027, 0, -22532, 4112, 0 },  /* ROOM3061 (inbound-door) */
    { -11840, 0, -18140, 3360, 0 },  /* ROOM3070 (inbound-door) */
    { -11840, 0, -18140, 3360, 0 },  /* ROOM3071 (inbound-door) */
    { -25850, 0, -25900, 930, 0 },  /* ROOM3080 (inbound-door) */
    { -25850, 0, -25900, 930, 0 },  /* ROOM3081 (inbound-door) */
    { -24731, 0, 887, 1024, 0 },  /* ROOM3090 (inbound-door) */
    { -24731, 0, 887, 1024, 0 },  /* ROOM3091 (inbound-door) */
    { -25500, 0, 11700, 0, 0 },  /* ROOM30A0 (inbound-door) */
    { -25500, 0, 11700, 0, 0 },  /* ROOM30A1 (inbound-door) */
    { -23100, 0, -24400, 0, 0 },  /* ROOM30B0 (inbound-door) */
    { -23100, 0, -24400, 0, 0 },  /* ROOM30B1 (inbound-door) */
    { -11250, 0, -10900, 3072, 0 },  /* ROOM30C0 (inbound-door) */
    { -11250, 0, -10900, 3072, 0 },  /* ROOM30C1 (inbound-door) */
    { -26300, 0, -22550, 0, 15 },  /* ROOM30D0 (inbound-door) */
    { -26300, 0, -22550, 0, 15 },  /* ROOM30D1 (inbound-door) */
    { -19406, 0, -22938, 2000, 0 },  /* ROOM30E0 (inbound-door) */
    { -19406, 0, -22938, 2000, 0 },  /* ROOM30E1 (inbound-door) */
    { 0, 0, 0, 0, 0 },  /* ROOM30F0 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM30F1 (no inbound door, no FLR) */
    { -13770, 0, -23540, 0, 0 },  /* ROOM4000 (FLR-floor) */
    { -13770, 0, -23540, 0, 0 },  /* ROOM4001 (FLR-floor) */
    { -21044, 0, -24000, -2048, 0 },  /* ROOM4010 (inbound-door) */
    { -21044, 0, -24000, -2048, 0 },  /* ROOM4011 (inbound-door) */
    { -21400, 0, -23400, 2048, 0 },  /* ROOM4020 (inbound-door) */
    { -21400, 0, -23400, 2048, 0 },  /* ROOM4021 (inbound-door) */
    { -23066, 0, -19748, 1104, 0 },  /* ROOM4030 (inbound-door) */
    { -23066, 0, -19748, 1104, 0 },  /* ROOM4031 (inbound-door) */
    { -26400, 0, 17150, 0, 0 },  /* ROOM4040 (inbound-door) */
    { -26400, 0, 17150, 0, 0 },  /* ROOM4041 (inbound-door) */
    { 8850, 0, -10650, 3072, 2 },  /* ROOM4050 (inbound-door) */
    { 8850, 0, -10650, 3072, 2 },  /* ROOM4051 (inbound-door) */
    { 0, 0, 0, 0, 0 },  /* ROOM4060 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM4061 (no inbound door, no FLR) */
    { -12100, -21600, -18950, 0, 0 },  /* ROOM4070 (inbound-door) */
    { -12100, -21600, -18950, 0, 0 },  /* ROOM4071 (inbound-door) */
    { 22000, 0, -5450, 0, 0 },  /* ROOM4080 (inbound-door) */
    { 22000, 0, -5450, 0, 0 },  /* ROOM4081 (inbound-door) */
    { -21022, 0, -24100, 2056, 0 },  /* ROOM4090 (inbound-door) */
    { -21022, 0, -24100, 2056, 0 },  /* ROOM4091 (inbound-door) */
    { -24700, 0, -14400, 247, 0 },  /* ROOM40A0 (inbound-door) */
    { -24700, 0, -14400, 247, 0 },  /* ROOM40A1 (inbound-door) */
    { -18750, 0, -14650, 2048, 1 },  /* ROOM40B0 (inbound-door) */
    { -18750, 0, -14650, 2048, 1 },  /* ROOM40B1 (inbound-door) */
    { 0, 0, 0, 0, 0 },  /* ROOM40C0 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM40C1 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM40D0 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM40D1 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM40E0 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM40E1 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM40F0 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM40F1 (no inbound door, no FLR) */
    { -10325, 0, -4275, 0, 0 },  /* ROOM5000 (FLR-floor) */
    { -10325, 0, -4275, 0, 0 },  /* ROOM5001 (FLR-floor) */
    { -23636, 0, -18240, 456, 0 },  /* ROOM5010 (inbound-door) */
    { -23636, 0, -18240, 456, 0 },  /* ROOM5011 (inbound-door) */
    { -12300, 0, -25800, 3072, 1 },  /* ROOM5020 (inbound-door) */
    { -12300, 0, -25800, 3072, 1 },  /* ROOM5021 (inbound-door) */
    { -13846, 0, -5474, 798, 2 },  /* ROOM5030 (inbound-door) */
    { -13846, 0, -5474, 798, 2 },  /* ROOM5031 (inbound-door) */
    { 1754, 0, -14789, 2048, 0 },  /* ROOM5040 (inbound-door) */
    { 1754, 0, -14789, 2048, 0 },  /* ROOM5041 (inbound-door) */
    { -25600, 0, -18400, 0, 0 },  /* ROOM5050 (inbound-door) */
    { -25600, 0, -18400, 0, 0 },  /* ROOM5051 (inbound-door) */
    { -25500, 0, -11100, 3680, 0 },  /* ROOM5060 (inbound-door) */
    { -25500, 0, -11100, 3680, 0 },  /* ROOM5061 (inbound-door) */
    { 1700, 0, -5700, 2048, 0 },  /* ROOM5070 (inbound-door) */
    { 1700, 0, -5700, 2048, 0 },  /* ROOM5071 (inbound-door) */
    { -9950, 0, -18200, 2048, 0 },  /* ROOM5080 (inbound-door) */
    { -9950, 0, -18200, 2048, 0 },  /* ROOM5081 (inbound-door) */
    { 24700, 0, -9250, 2048, 9 },  /* ROOM5090 (inbound-door) */
    { 24700, 0, -9250, 2048, 9 },  /* ROOM5091 (inbound-door) */
    { -23878, 0, -16268, 1501, 11 },  /* ROOM50A0 (inbound-door) */
    { -23878, 0, -16268, 1501, 11 },  /* ROOM50A1 (inbound-door) */
    { -14100, 0, -26150, 3072, 0 },  /* ROOM50B0 (inbound-door) */
    { -14100, 0, -26150, 3072, 0 },  /* ROOM50B1 (inbound-door) */
    { -6975, 0, -10005, 152, 0 },  /* ROOM50C0 (inbound-door) */
    { -6975, 0, -10005, 152, 0 },  /* ROOM50C1 (inbound-door) */
    { -23437, -5400, -4400, 4712, 0 },  /* ROOM50D0 (inbound-door) */
    { -23437, -5400, -4400, 4712, 0 },  /* ROOM50D1 (inbound-door) */
    { -25450, 0, -14700, 0, 0 },  /* ROOM50E0 (inbound-door) */
    { -25450, 0, -14700, 0, 0 },  /* ROOM50E1 (inbound-door) */
    { -24550, 0, -23650, 0, 1 },  /* ROOM50F0 (inbound-door) */
    { -24550, 0, -23650, 0, 1 },  /* ROOM50F1 (inbound-door) */
    { -23668, 0, -16619, 2048, 0 },  /* ROOM5100 (inbound-door) */
    { -23668, 0, -16619, 2048, 0 },  /* ROOM5101 (inbound-door) */
    { -13846, 0, -5474, 798, 2 },  /* ROOM5110 (inbound-door) */
    { -13846, 0, -5474, 798, 2 },  /* ROOM5111 (inbound-door) */
    { -24594, 0, -969, 1231, 5 },  /* ROOM5120 (inbound-door) */
    { -24594, 0, -969, 1231, 5 },  /* ROOM5121 (inbound-door) */
    { 1700, 0, -5700, 2048, 0 },  /* ROOM5130 (inbound-door) */
    { 1700, 0, -5700, 2048, 0 },  /* ROOM5131 (inbound-door) */
    { 15368, 0, -9944, 1080, 13 },  /* ROOM5140 (inbound-door) */
    { 15368, 0, -9944, 1080, 13 },  /* ROOM5141 (inbound-door) */
    { 0, 0, 0, 0, 0 },  /* ROOM5150 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM5151 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM5160 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM5161 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM5170 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM5171 (no inbound door, no FLR) */
    { 7186, 0, -9289, 0, 0 },  /* ROOM6000 (FLR-floor) */
    { 7186, 0, -9289, 0, 0 },  /* ROOM6001 (FLR-floor) */
    { -26350, 0, -25900, 0, 7 },  /* ROOM6010 (inbound-door) */
    { -26350, 0, -25900, 0, 7 },  /* ROOM6011 (inbound-door) */
    { -4500, 0, 2300, 3072, 0 },  /* ROOM6020 (inbound-door) */
    { -4500, 0, 2300, 3072, 0 },  /* ROOM6021 (inbound-door) */
    { -26450, 0, -23350, 0, 12 },  /* ROOM6030 (inbound-door) */
    { -26450, 0, -23350, 0, 12 },  /* ROOM6031 (inbound-door) */
    { -26214, 0, -3861, 0, 0 },  /* ROOM6040 (inbound-door) */
    { -26214, 0, -3861, 0, 0 },  /* ROOM6041 (inbound-door) */
    { 0, 0, 0, 0, 0 },  /* ROOM6050 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM6051 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM6060 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM6061 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM6070 (no inbound door, no FLR) */
    { 0, 0, 0, 0, 0 },  /* ROOM6071 (no inbound door, no FLR) */
};
#endif
