# Hand-Mutanten der Gegenpruefung R4-2 (Linse Umgehung): je (Name, [(alt, neu, Anzahl alt im Gate)])
# Klasse D: Konstanten auf Modulebene (die AST-Klassen erfassen nur Funktionen) und strip/split/fullmatch-Varianten,
# die ein Entwickler bei einer gewollten Aenderung plausibel einbaut (danach neu pinnen = dokumentierter Weg).
HAND = [
    ("D01_SEGMENT_MAX_252", [("SEGMENT_MAX = 251 ", "SEGMENT_MAX = 252 ", 1)]),
    ("D02_SEGMENT_MAX_255", [("SEGMENT_MAX = 251 ", "SEGMENT_MAX = 255 ", 1)]),
    ("D03_PFAD_MAX_513", [("PFAD_MAX = 512 ", "PFAD_MAX = 513 ", 1)]),
    ("D04_PFAD_MAX_4096", [("PFAD_MAX = 512 ", "PFAD_MAX = 4096", 1)]),
    ("D05_NEU_ENDUNG_new", [('NEU_ENDUNG = b".neu"', 'NEU_ENDUNG = b".new"', 1)]),
    ("D06_ASCII_KLEIN_ohne_Z", [('bytes.maketrans(b"ABCDEFGHIJKLMNOPQRSTUVWXYZ", b"abcdefghijklmnopqrstuvwxyz")',
                                'bytes.maketrans(b"ABCDEFGHIJKLMNOPQRSTUVWXY", b"abcdefghijklmnopqrstuvwxy")', 1)]),
    ("D07_KOPF_RE_plus_beide", [('rb"# re15 assets v2 ([0-9]{1,18}) ([0-9]{1,18})"',
                                 'rb"# re15 assets v2 ([0-9]+) ([0-9]+)"', 1)]),
    ("D08_KOPF_RE_plus_anzahl", [('rb"# re15 assets v2 ([0-9]{1,18}) ([0-9]{1,18})"',
                                  'rb"# re15 assets v2 ([0-9]+) ([0-9]{1,18})"', 1)]),
    ("D09_GROESSE_RE_19", [('GROESSE_RE = re.compile(rb"[0-9]{1,18}")', 'GROESSE_RE = re.compile(rb"[0-9]{1,19}")', 1)]),
    ("D10_SHA_RE_gross", [('SHA_RE = re.compile(rb"[0-9a-f]{64}")', 'SHA_RE = re.compile(rb"[0-9a-fA-F]{64}")', 1)]),
    ("D11_SHA_RE_64plus", [('SHA_RE = re.compile(rb"[0-9a-f]{64}")', 'SHA_RE = re.compile(rb"[0-9a-f]{64,}")', 1)]),
    ("D12_split_splitlines", [('zeilen = roh.split(b"\\n")', 'zeilen = roh.splitlines()', 1)]),
    ("D13_kopf_strip_cr", [('kopf = zeilen[0].rstrip(b"\\r")', 'kopf = zeilen[0].strip(b"\\r")', 1)]),
    ("D14_kopf_rstrip_alles", [('kopf = zeilen[0].rstrip(b"\\r")', 'kopf = zeilen[0].rstrip()', 1)]),
    ("D15_zeile_strip_cr", [('z = z.rstrip(b"\\r")', 'z = z.strip(b"\\r")', 1)]),
    ("D16_zeile_rstrip_alles", [('z = z.rstrip(b"\\r")', 'z = z.rstrip()', 1)]),
    ("D17_zeile_rstrip_cr_lf_tab", [('z = z.rstrip(b"\\r")', 'z = z.rstrip(b"\\r\\n\\t")', 1)]),
    ("D18_tab_split_ohne_max", [('teile = z.split(b"\\t", 2)', 'teile = z.split(b"\\t")', 1)]),
    ("D19_befunde_ab_2", [("    if n_befunde:\n", "    if n_befunde > 1:\n", 1)]),
    ("D20_segmente_ohne_letztes", [('    lang = max(len(t) for t in teile)', '    lang = max(len(t) for t in teile[:-1] or [b""])', 1)]),
    ("D21_segmente_ohne_erstes", [('    lang = max(len(t) for t in teile)', '    lang = max(len(t) for t in teile[1:] or [b""])', 1)]),
    ("D22_punkt_ohne_erstes", [('if any(t in (b"", b".", b"..") for t in teile):',
                                'if any(t in (b"", b".", b"..") for t in teile[1:]):', 1)]),
    ("D23_punkt_ohne_letztes", [('if any(t in (b"", b".", b"..") for t in teile):',
                                 'if any(t in (b"", b".", b"..") for t in teile[:-1]):', 1)]),
    ("D24_neu_ohne_faltung", [('if p[-len(NEU_ENDUNG):].translate(_ASCII_KLEIN) == NEU_ENDUNG:',
                               'if p[-len(NEU_ENDUNG):] == NEU_ENDUNG:', 1)]),
    ("D25_neu_je_segment", [('if p[-len(NEU_ENDUNG):].translate(_ASCII_KLEIN) == NEU_ENDUNG:',
                             'if any(t.translate(_ASCII_KLEIN).endswith(NEU_ENDUNG) for t in teile):', 1)]),
    ("D26_quell_ohne_faltung", [('klein.setdefault(roh.translate(_ASCII_KLEIN), []).append(rel)',
                                 'klein.setdefault(roh, []).append(rel)', 1)]),
    ("D27_man_ohne_faltung", [('klein.setdefault(p.encode("utf-8").translate(_ASCII_KLEIN), []).append(p)',
                               'klein.setdefault(p.encode("utf-8"), []).append(p)', 1)]),
    ("D28_quell_mit_assets_praefix", [('roh = name[len("assets/"):].encode("utf-8", "surrogateescape")',
                                       'roh = name.encode("utf-8", "surrogateescape")', 1)]),
    ("D29_man_lower_statt_ascii", [('klein.setdefault(p.encode("utf-8").translate(_ASCII_KLEIN), []).append(p)',
                                    'klein.setdefault(p.lower(), []).append(p)', 1)]),
]
