#!/usr/bin/env python3
"""tuerton_bauen.py - Spur K (Runde 35): der Tonteil des RE2-Tuerarchivs DOOR13 als gen/cut10f0_tuerton.inc.

Warum DOOR13: die Tuer ROOM10F0 Slot 0 (main00 @0x00F32) -> ROOM10D0 spielt im Port die RE2-Sequenz
DOOR13 (gen/tuer_zuordnung.inc Zeile ROOM10F0 Slot 0: Archiv 0x13). "Marvin kommt durch die Tuer -
Tuer knallen Sound" (AUFTRAG.md Z.48) = der Door_exit-Satz (se 1) GENAU DIESES Archivs — derselbe Ton,
den der Spieler hoert, wenn er selbst durch diese Tuer geht (Sound ist RE2, VERTRAG §2.2).
Tonteil = Datei[0 .. 0x3DA8) laut RE2-Archivtabelle @0x8009A604 (gen/re2_tuer_tabelle.inc DOOR13:
`a8 3d 04 95 08 00 00 00 96 c1 00 00`), Bytes UNVERAENDERT aus shared_assets/RE2/DOOR/DOOR13.DO2
(54532 B); Aufbau wie TORSE (EDT 0xC38 + VB), Lader re15_audio_re2_tuer_laden (audio_pc.c).
Beim echten Eintritt durch die Tuer liegt dieser Tonteil ohnehin schon in der Tuerbank (sie
ueberlebt re15_audio_load_room_banks); die eingebackene Kopie deckt den Debug-Sprung/CONTINUE ab.
"""
import hashlib, os

HIER = os.path.dirname(os.path.abspath(__file__))
PORT = os.path.dirname(os.path.dirname(HIER))
SRC = os.path.join(PORT, "shared_assets", "RE2", "DOOR", "DOOR13.DO2")
OUT = os.path.join(PORT, "engine", "src", "gen", "cut10f0_tuerton.inc")
TON = 0x3DA8   # @0x8009A604 Halbwort 0

d = open(SRC, "rb").read()
assert len(d) == 54532, len(d)
ton = d[:TON]
sha = hashlib.sha1(ton).hexdigest()
lines = ["/* AUTO-GENERATED by re15_port/tools/r35_k/tuerton_bauen.py -- DO NOT EDIT.",
         " * Tonteil von shared_assets/RE2/DOOR/DOOR13.DO2 [0 .. 0x%04X) (RE2-Archivtabelle @0x8009A604)," % TON,
         " * bytegleich; sha1 %s. Satz 0 = Skript-Se_on (oeffnen), Satz 1 = Door_exit (zufallen). */" % sha,
         "#define RE15_CUT10F0_TUERTON_LEN %d" % len(ton),
         "static const uint8_t k_cut10f0_tuerton[RE15_CUT10F0_TUERTON_LEN] = {"]
for i in range(0, len(ton), 16):
    lines.append("    " + ", ".join("0x%02x" % b for b in ton[i:i + 16]) + ",")
lines.append("};")
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print("-> %s: %d Bytes, sha1 %s" % (OUT, len(ton), sha))
