#!/usr/bin/env python3
# gen_trig_lut.py - regenerate engine/src/re15_trig_lut.c from the byte-true RE1.5 sin/cos table
# DAT_800794c4 in PSX.EXE. Run from the repo root: python re15_port/tools/gen_trig_lut.py
#
# The table is 4096 words, one per PSX angle unit (4096 = 360 deg); each word = (cos16 << 16) | sin16,
# both signed Q12 (4096 = 1.0). BYTE-TRUE audit #2: the old skeleton_trig_pc.c used sinf/cosf +
# (int)(x*4096) truncation, which diverged from this table (round vs trunc, plus a systematic cos
# bias) and fed the reported pixel-shift. Both PC and PSX now read this table via re15_sin/cos_q12.
import struct, sys

EXE = 'info/Re1.5/PSX.EXE'
LUT_ADDR = 0x800794c4
FILE_OFF = 0x800 + (LUT_ADDR - 0x80010000)   # PSX.EXE load base 0x80010000, 0x800 header
N = 4096

with open(EXE, 'rb') as f:
    f.seek(FILE_OFF)
    raw = f.read(N * 4)
words = list(struct.unpack('<%dI' % N, raw))

def s16(x):
    x &= 0xffff
    return x - 0x10000 if x >= 0x8000 else x

# self-check: the four cardinal angles must be exact
assert s16(words[0] & 0xffff) == 0 and s16(words[0] >> 16) == 4096
assert s16(words[1024] & 0xffff) == 4096 and s16(words[1024] >> 16) == 0
assert s16(words[2048] & 0xffff) == 0 and s16(words[2048] >> 16) == -4096
assert s16(words[3072] & 0xffff) == -4096 and s16(words[3072] >> 16) == 0
print("LUT self-check OK", file=sys.stderr)

out = []
out.append("/* re15_trig_lut.c - the byte-true RE1.5 sin/cos table (DAT_800794c4 @PSX.EXE).")
out.append(" * AUTO-GENERATED by re15_port/tools/gen_trig_lut.py from info/Re1.5/PSX.EXE - do not hand-edit.")
out.append(" * 4096 words, one per PSX angle unit (4096 = 360 deg); each word = (cos16 << 16) | sin16,")
out.append(" * both signed Q12 (4096 = 1.0). BYTE-TRUE audit #2: the old sinf/cosf + (int)(x*4096)")
out.append(" * truncation diverged from this table (round vs trunc + a systematic cos bias) and fed the")
out.append(" * reported pixel-shift; both platforms now read this table. */")
out.append('#include "re15_skeleton.h"')
out.append("")
out.append("const uint32_t re15_trig_lut[4096] = {")
for i in range(0, N, 8):
    out.append("    " + ", ".join("0x%08xu" % words[j] for j in range(i, i + 8)) + ",")
out.append("};")
out.append("")
out.append("/* angle may be any int (negative / >4096); the original masks to the 4096-word table.")
out.append(" * sin = low 16 (sign-extended), cos = high 16. Byte-true DAT_800794c4 lookup. */")
out.append("int re15_sin_q12(int angle_4096)")
out.append("{")
out.append("    uint32_t w = re15_trig_lut[(uint32_t)angle_4096 & 0xfff];")
out.append("    return (int)(int16_t)(w & 0xffff);")
out.append("}")
out.append("int re15_cos_q12(int angle_4096)")
out.append("{")
out.append("    uint32_t w = re15_trig_lut[(uint32_t)angle_4096 & 0xfff];")
out.append("    return (int)(int16_t)(w >> 16);")
out.append("}")
out.append("")

with open('re15_port/engine/src/re15_trig_lut.c', 'w', newline='\n') as f:
    f.write("\n".join(out))
print("wrote re15_port/engine/src/re15_trig_lut.c (%d words)" % N, file=sys.stderr)
