#!/usr/bin/env python3
"""Generate engine/src/gen/inv_name_bank.inc — the byte-true ITEM-NAME string bank
for the status screen's grid-mode name print (wave 2).

Source: re15_port/shared_assets/PSX/BIN/DEBUG.BIN. The DEBUG.BIN module maps to RAM
@0x800c0000 (file offset = addr - 0x800c0000), byte-verified against the savestate RAM
extraction of stage_saves/mzd_inv_open.sav: the per-glyph width table @0x800c4416
(== include/font_width.h), the name offset table @0x800c495c and blob @0x800c4a28
(== gen/item_prompt_data.inc) are all byte-identical file<->RAM.
Die Tabelle hat 102 Eintraege, nicht 52: sie endet physisch am Blob-Anfang
((0x800c4a28-0x800c495c)/2), und FUN_80028840 hat keinerlei Bereichspruefung
(andi a0,a0,0xff / sll a0,a0,1 / lhu 0x800c495c+id*2 / addu 0x800c4a28).

Tables (spec shots/inv_wave2_spec.md Task D):
  - name offsets: 102 u16 @0x800c495c (ids 0x00..0x65; FUN_80028840 @0x80028844:
    ptr = 0x800c4a28 + u16[0x800c495c + id*2])
  - name blob    @0x800c4a28 (terminator glyph 0x07)
  - digraph pair table for the stream decoder FUN_80013160 @0x80013160: codes with
    (c+0xa0)&0xff <= 0x58 (= 0x60..0xb8) expand via pair @0x800c44b8+(c-0xa0)*2
    (first half) / @0x800c44b9+... (second half, stashed in the pending u16
    @0x800c44b6). Vendored as the region [0x800c4438, 0x800c44ea) with bias +0x80.
"""
import struct, sys, os

ROOT = os.path.join(os.path.dirname(__file__), "..")
SRC = os.path.join(ROOT, "shared_assets", "PSX", "BIN", "DEBUG.BIN")
OUT = os.path.join(ROOT, "engine", "src", "gen", "inv_name_bank.inc")

BASE = 0x800C0000
OFF_TBL = 0x800C495C - BASE
BLOB = 0x800C4A28 - BASE
DIGRAPH_LO = 0x800C4438 - BASE     # (c-0xa0)*2 min = (0x60-0xa0)*2 = -0x80 from 0x44b8
DIGRAPH_HI = 0x800C44EA - BASE     # (0xb8-0xa0)*2+2 = +0x32 from 0x44b8
NIDS = (0x800C4A28 - 0x800C495C) // 2   # 102 Eintraege (IDs 0x00..0x65) — die Offsettabelle
                                   # endet physisch am Blob; Reader FUN_80028840 @0x80028840 hat
                                   # KEINE Bereichspruefung (andi a0,a0,0xff / sll / lhu / addu).

d = open(SRC, "rb").read()
offs = struct.unpack_from("<%dH" % NIDS, d, OFF_TBL)

# blob extent: walk from the last offset to its 0x07 terminator
end = BLOB + offs[NIDS - 1]
while d[end] != 0x07:
    end += 1
end += 1  # include the terminator
blob = d[BLOB:end]
pairs = d[DIGRAPH_LO:DIGRAPH_HI]

def carr(b):
    return ",".join("0x%02x" % x for x in b)

with open(OUT, "w") as f:
    f.write("/* GENERATED by tools/gen_inv_name_bank.py from shared_assets/PSX/BIN/DEBUG.BIN\n"
            " * (module maps @0x800c0000; byte-verified == mzd_inv_open.sav RAM). DO NOT EDIT.\n"
            " * Name offsets %d u16 @0x800c495c (die Tabelle endet physisch am Blob; Reader\n"
            " * FUN_80028840 @0x80028840 hat KEINE Bereichspruefung); blob @0x800c4a28;\n"
            " * digraph pairs [0x800c4438,0x800c44ea) for FUN_80013160 (base 0x800c44b8\n"
            " * = bias +0x80). */\n" % NIDS)
    f.write("#define RE15_INV_NAME_NIDS %d\n" % NIDS)
    f.write("#define RE15_INV_NAME_DIGRAPH_BIAS 0x80\n")
    f.write("static const unsigned short re15_inv_name_off[%d] = {%s};\n"
            % (NIDS, ",".join("0x%x" % o for o in offs)))
    f.write("static const unsigned char re15_inv_name_blob[%d] = {%s};\n" % (len(blob), carr(blob)))
    f.write("static const unsigned char re15_inv_name_digraph[%d] = {%s};\n" % (len(pairs), carr(pairs)))

print("wrote", OUT, "blob", len(blob), "pairs", len(pairs))
