#!/usr/bin/env python3
"""Generate engine/src/gen/inv_desc_bank.inc — the byte-true item-DESCRIPTION string
bank for the status screen's CHECK/examine message (wave 4).

Source: re15_port/shared_assets/PSX/BIN/DEBUG.BIN. The DEBUG.BIN module maps to RAM
@0x800c0000 (file offset = addr - 0x800c0000), byte-verified file==RAM against
stage_saves/mzd_inv_open.sav for the whole CHECK region this wave (0x800c6220/0x800c6630/
0x800c0258 ranges).

Bank (wave-4 disasm of FUN_800c6630 + FUN_80027e68):
  - base @0x800c50de; string resolve (FUN_80027e68, a1&0xc00==0x400 path):
    ptr = 0x800c50de + u16[0x800c50de + entry*2].
  - entry INDEX = the ITEM ID (the CHECK FSM passes a2 = cursor item id from helper
    0x800c6600 @0x800c6734; id 0 = "You can't use it here." doubles as the cant-use
    message). 72 entries (u16[0]=0x90 -> 0x90/2 = 72 = ids 0x00..0x47).
  - stream codes (msg VM FUN_80028134 + emitter FUN_80028868): 0x00 = space,
    0x01 0x00 = end -> VM state 5 press-wait, 0x02 0x00 = page-wait -> VM state 2,
    0x08 = newline (emitter: x:=DAT_800b8534, y+=16 @FUN_80028868 case 8),
    0x0c..0xf7 = glyph (atlas cell u=(c&0xf)<<4, v=((c>>4)<<4)+0x20).
    Bank-wide control census (this generator asserts it): ONLY 0x01/0x02/0x08 occur.
"""
import struct, os

ROOT = os.path.join(os.path.dirname(__file__), "..")
SRC = os.path.join(ROOT, "shared_assets", "PSX", "BIN", "DEBUG.BIN")
OUT = os.path.join(ROOT, "engine", "src", "gen", "inv_desc_bank.inc")

BASE = 0x800C0000
BANK = 0x800C50DE - BASE

d = open(SRC, "rb").read()
first = struct.unpack_from("<H", d, BANK)[0]
assert first == 0x90, "entry-0 offset must be 0x90 (@0x800c50de)"
NIDS = first // 2                       # 72 (ids 0x00..0x47)
offs = struct.unpack_from("<%dH" % NIDS, d, BANK)

# blob extent: walk every entry to its 01 00 terminator; assert the control census.
end = BANK
for idx in range(NIDS):
    i = BANK + offs[idx]
    while True:
        c = d[i]
        if c == 0x01:
            assert d[i + 1] == 0x00, "END operand must be 0 (press-wait) @entry %d" % idx
            i += 2
            break
        elif c == 0x02:
            assert d[i + 1] == 0x00, "PAGE operand must be 0 @entry %d" % idx
            i += 2
        elif c == 0x08:
            i += 1
        else:
            assert c == 0x00 or 0x0c <= c <= 0xf7, \
                "unexpected code 0x%02x @entry %d" % (c, idx)
            i += 1
    end = max(end, i)
blob = d[BANK:end]                       # offsets are relative to the bank base

with open(OUT, "w") as f:
    f.write("/* GENERATED by tools/gen_inv_desc_bank.py from shared_assets/PSX/BIN/DEBUG.BIN\n"
            " * (module maps @0x800c0000; file==RAM byte-verified vs mzd_inv_open.sav). DO NOT\n"
            " * EDIT. Desc bank @0x800c50de: 72 u16 entry offsets (INDEX = ITEM ID; entry 0 =\n"
            " * the cant-use text), strings glyph-coded (chr = code+0x24), controls 0x00=space\n"
            " * 0x01 0x00=end 0x02 0x00=page-wait 0x08=newline (msg VM FUN_80028134). */\n")
    f.write("#define RE15_INV_DESC_NIDS %d\n" % NIDS)
    f.write("static const unsigned short re15_inv_desc_off[%d] = {%s};\n"
            % (NIDS, ",".join("0x%x" % o for o in offs)))
    f.write("static const unsigned char re15_inv_desc_blob[%d] = {%s};\n"
            % (len(blob), ",".join("0x%02x" % x for x in blob)))

print("wrote", OUT, "entries", NIDS, "blob", len(blob))
