#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_re15_elev_anchors.py — erzeugt engine/src/gen/re15_elev_se.inc.

Die ANKER kommen aus den DATEN, nicht aus einer Raumnummer im Code.

Gesucht wird die 32-Byte-Folge, die in RE1.5 GENAU eine Fahrstuhl-Fahrt ist
(selbst gemessen 2026-09-26 ueber alle 240 RE1.5-RDTs und alle 250 RE2-RDTs):

  22 01 1c 01   Set   bank1 bit28 = 1     <- hier setzt RE2 Se_on(bank2, id 0x11)
  09 0a 08 00   Sleep 8
  22 01 1c 00   Set   bank1 bit28 = 0
  09 0a 5a 00   Sleep 90                  = DIE FAHRT
  22 01 1c 01   Set   bank1 bit28 = 1     <- hier setzt RE2 Se_on(bank2, id 0x12)
  09 0a 08 00   Sleep 8
  22 01 1c 00   Set   bank1 bit28 = 0
  09 0a 14 00   Sleep 20                  = ANKUNFT

Warum die VOLLEN 32 Byte und nicht 16: die zweite Haelfte allein
(`...09 0a 14 00`) steht auch in ROOM5090/5091/6030/6031 (RE1.5) und in
RE2 ROOM4080 — gemessen. Erst die zusammenhaengenden 32 Byte sind eindeutig:
4 Dateien, je 3 Treffer, 0 Fehltreffer in beiden Baeumen.

RE2-Beleg fuer die Zuordnung der beiden Ids (info/re2leon/PL0/RDT/ROOM21B0.RDT,
selbst gelesen): @0x2756 `36 02 11 01 01 00 00 00 00 00 00 00` steht unmittelbar
vor dem ersten Puls @0x2762, @0x2784 `36 02 12 ...` unmittelbar vor dem zweiten
@0x2790. Operanden-Layout: LAB_80041624 @0x80041644 `lbu a3,1(s0)` = bank,
@0x80041648 `lh a0,2(s0)` = id -> bank 2 = SND0, id 0x11 / 0x12.

⛔ Der Ton ist eine RE2-ERGAENZUNG. RE1.5 ist hier stumm (kein Se_on im Skript;
   die 11 bzw. 12 direkten SE-Emitter-Rufe in STAGE1.BIN/STAGE4.BIN sitzen
   ausschliesslich in Gegner-Zustandsroutinen, und die vier Fahrstuhlraeume
   spawnen keinen einzigen Gegner — Details im Kopf von scd_elev_se.c).
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
ASSETS = os.path.join(REPO, "re15_port", "shared_assets", "PSX")
OUT = os.path.join(REPO, "re15_port", "engine", "src", "gen", "re15_elev_se.inc")

SIG = bytes.fromhex("22011c01090a080022011c00090a5a00"
                    "22011c01090a080022011c00090a1400")
SE_FIRST = 0x11     # Puls 1 (Signatur-Offset 0x00) -> Fahrgeraeusch
SE_SECOND = 0x12    # Puls 2 (Signatur-Offset 0x10) -> Ankunft


def main():
    hits = []
    n_rdt = 0
    for dp, _dn, fn in os.walk(ASSETS):
        for f in sorted(fn):
            if not f.upper().endswith(".RDT"):
                continue
            n_rdt += 1
            p = os.path.join(dp, f)
            d = open(p, "rb").read()
            i = d.find(SIG)
            while i >= 0:
                try:
                    room = int(f[4:8], 16)
                except ValueError:
                    room = 0
                hits.append((room, i, f))
                i = d.find(SIG, i + 1)
    hits.sort()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", newline="\n") as o:
        o.write("/* AUTO-GENERATED by re15_port/tools/gen_re15_elev_anchors.py -- DO NOT EDIT.\n"
                " * Quelle: alle ROOM*.RDT unter re15_port/shared_assets/PSX (%d RDTs durchsucht).\n"
                " * Siehe den Generator-Kopf fuer die Belege. */\n\n" % n_rdt)
        o.write("/* Die 32-Byte-Fahrt-Signatur (Set/Sleep-Doppelpuls). */\n")
        o.write("#define RE15_ELEV_SIG_LEN %d\n" % len(SIG))
        o.write("static const unsigned char s_re15_elev_sig[RE15_ELEV_SIG_LEN] = {\n")
        for r in range(0, len(SIG), 8):
            o.write("    " + ", ".join("0x%02x" % c for c in SIG[r:r + 8]) + ",\n")
        o.write("};\n\n")
        o.write("/* Signatur-Offset -> RE2-SE-Id (ROOM21B0.RDT @0x2756 / @0x2784). */\n")
        o.write("#define RE15_ELEV_SE_FIRST  0x%02X   /* Puls 1 @sig+0x00  = Fahrt   */\n" % SE_FIRST)
        o.write("#define RE15_ELEV_SE_SECOND 0x%02X   /* Puls 2 @sig+0x10  = Ankunft */\n" % SE_SECOND)
        o.write("#define RE15_ELEV_SECOND_DELTA 0x10\n\n")
        o.write("/* GEMESSENE Fundstellen — nur fuer den Riegel (tests), nicht fuer die Laufzeit:\n"
                " * die Laufzeit sucht die Signatur im geladenen RDT-Puffer selbst. */\n")
        o.write("#define RE15_ELEV_HIT_COUNT %d\n" % len(hits))
        o.write("typedef struct { unsigned short room; unsigned int off; } re15_elev_hit_t;\n")
        o.write("static const re15_elev_hit_t s_re15_elev_hits[RE15_ELEV_HIT_COUNT] = {\n")
        for room, off, f in hits:
            o.write("    { 0x%04X, 0x%04X },   /* %s */\n" % (room, off, f))
        o.write("};\n")
    print("%d RDTs durchsucht, %d Fundstellen -> %s" % (n_rdt, len(hits), OUT))
    for room, off, f in hits:
        print("  %s  0x%04X" % (f, off))
    return 0


if __name__ == "__main__":
    sys.exit(main())
