#!/usr/bin/env python3
"""Generate engine/src/gen/item_prompt_data.inc — die byte-true Item-Namens- und
Prompt-Skript-Tabellen des Originals.

QUELLE: re15_port/shared_assets/PSX/BIN/DEBUG.BIN. Das Modul mappt nach RAM @0x800c0000
(file_off = addr - 0x800c0000). Byte-verifiziert gegen die Savestate-RAM-Extraktion
(vgl. tools/gen_inv_name_bank.py: Glyphen-Breitentabelle @0x800c4416, Namens-Offsettabelle
@0x800c495c und Blob @0x800c4a28 sind datei<->RAM identisch).

WARUM DIESER GENERATOR EXISTIERT (Nutzer-Report 2026-08-27: "beim Nehmen des Feuerloeschers
room 1000 steht noch 'will you take ?'"):
Die Vorgaengerfassung von item_prompt_data.inc war ein Savestate-Auszug mit nur 48 Namen und
4 von 8 Prompt-Skripten. Der Feuerloescher ist Item 0x31 (= 49) und fiel damit aus der Tabelle;
item_prompt_common.c setzte den Namen dann STILLSCHWEIGEND nicht ein.
Beleg Item-ID: ROOM1000.RDT Datei-Offset 0xC24 = Item_aot_set (Opcode 0x50), Rumpf
  50 03 09 31 00 00 14 50 e0 fc 20 03 20 03 | 31 00 | 01 00
  -> pc[14] @0xC32 = 0x31 = Item-Typ, pc[16] @0xC34 = 0x01 = Anzahl.
Beleg Name: DEBUG.BIN Offsettabelle-Eintrag 0x31 = 0x02b4 -> Blob @file 0x4cdc
  22 45 4e 41 00 21 54 50 45 4a 43 51 45 4f 44 41 4e = "Fire Extinguisher".

BELEG FUER DIE TABELLEN-GRENZEN (kein geratener Wert):
  Namens-Reader FUN_80028840 @0x80028840 — KEINE Bereichspruefung, nur ein Byte-Mask:
    80028840: andi  a0,a0,0xff
    80028844: sll   a0,a0,1
    8002884c: addiu at,at,18780      ; at = 0x800c495c  (Offsettabelle)
    80028854: lhu   v1,0(at)
    8002885c: addiu v0,v0,18984      ; v0 = 0x800c4a28  (Blob)
    80028864: addu  v0,v1,v0         ; return blob + u16-Offset
  Die Offsettabelle endet also physisch dort, wo der Blob beginnt:
    (0x800c4a28 - 0x800c495c) / 2 = 0xcc/2 = 102 Eintraege (IDs 0x00..0x65).
  Alle 102 Offsets sind streng monoton steigend und zeigen auf gueltige, mit 0x07 terminierte
  Namen — die Tabelle ist voll belegt, 102 ist keine Schaetzung.

  Prompt-Skript-Selektor FUN_80027e68 @0x80027f20 — Basis == Offsettabelle:
    80027f20: sll   v0,a2,1
    80027f30: addiu at,at,20422      ; at = 0x800c4fc6
    80027f34: addu  v0,v0,at
    80027f38: lhu   v0,0(v0)
    80027f44: addu  v0,v0,at         ; ptr = 0x800c4fc6 + u16[idx]
  (zweite identische Fundstelle @0x80028040-4c). Die 8 u16 ab 0x800c4fc6 lauten
  10 00 2f 00 50 00 6b 00 8b 00 a9 00 c5 00 f8 00; der kleinste (0x10) markiert das Ende
  der Tabelle selbst = 8 Skripte.

Skript-Inhalte (dekodiert, Steuer-Ops 01=END 02=YesNo-Branch 03=Seitenumbruch/YesNo
05=Farbe 06=Item-Namen einsetzen 08=Zeilenumbruch):
  [0] Will you take the <NAME>?        [1] You can't carry any more items.
  [2] You have used the <NAME>.        [3] Will you place the <NAME>?
  [4] Will you use the <NAME>?         [5] The <NAME> has been filed.
  [6] You don't need this key any more. Discard it?
  [7] Locked from the other side.
"""
import struct, sys, os

ROOT = os.path.join(os.path.dirname(__file__), "..")
SRC  = os.path.join(ROOT, "shared_assets", "PSX", "BIN", "DEBUG.BIN")
OUT  = os.path.join(ROOT, "engine", "src", "gen", "item_prompt_data.inc")

BASE      = 0x800C0000
NAME_OFF  = 0x800C495C          # u16[] — Ende == NAME_BLOB (FUN_80028840 @0x8002884c)
NAME_BLOB = 0x800C4A28          # Glyphen-Blob, Terminator 0x07 (@0x8002885c)
SCRIPT_TB = 0x800C4FC6          # u16[] UND Basis der Skripte (FUN_80027e68 @0x80027f30/f44)

d = open(SRC, "rb").read()

# ---- Namen ---------------------------------------------------------------------------------
NIDS = (NAME_BLOB - NAME_OFF) // 2                     # 0xcc/2 = 102, siehe Kopf
offs = struct.unpack_from("<%dH" % NIDS, d, NAME_OFF - BASE)
prev = -1
for i, o in enumerate(offs):                            # Grenze belegen, nicht behaupten
    assert o > prev or i == 0, "Namens-Offsets nicht monoton bei %d" % i
    prev = o
end = NAME_BLOB - BASE + offs[NIDS - 1]
while d[end] != 0x07:
    end += 1
end += 1                                                # Terminator einschliessen
name_blob = d[NAME_BLOB - BASE:end]

# ---- Prompt-Skripte ------------------------------------------------------------------------
first = struct.unpack_from("<H", d, SCRIPT_TB - BASE)[0]
NSCR  = first // 2                                      # kleinster Offset == Ende der Tabelle
soffs = struct.unpack_from("<%dH" % NSCR, d, SCRIPT_TB - BASE)
send  = SCRIPT_TB - BASE + max(soffs)
n = 0
while d[send] != 0x01:                                  # bis END des letzten Skripts
    if d[send] == 0x02: send += 2                       # Branch-Operanden ueberspringen
    send += 1
    n += 1
    assert n < 256, "Skript-Ende nicht gefunden"
send += 1
scr_blob = d[SCRIPT_TB - BASE:send]                     # inkl. der Offsettabelle am Kopf

def carr(b):
    return ",".join("0x%02x" % x for x in b)

with open(OUT, "w") as f:
    f.write("/* GENERATED by tools/gen_item_prompt_data.py from shared_assets/PSX/BIN/DEBUG.BIN\n"
            " * (Modul mappt @0x800c0000; byte-verifiziert == Savestate-RAM). DO NOT EDIT.\n"
            " *\n"
            " * Namens-Offsettabelle %d u16 @0x800c495c, Blob @0x800c4a28 (Terminator 0x07).\n"
            " *   Reader FUN_80028840: `andi a0,a0,0xff` / `sll a0,a0,1` / lhu @0x800c495c+id*2\n"
            " *   / addu 0x800c4a28 — KEINE Bereichspruefung; die Tabelle endet physisch am Blob:\n"
            " *   (0x800c4a28-0x800c495c)/2 = %d Eintraege (IDs 0x00..0x%02x).\n"
            " * Prompt-Skripte: %d u16 @0x800c4fc6, Offsets RELATIV ZUR TABELLE selbst\n"
            " *   (FUN_80027e68 @0x80027f30 `addiu at,at,20422` / @0x80027f38 `lhu` /\n"
            " *   @0x80027f44 `addu v0,v0,at`). script_blob[] beginnt AN der Tabelle, die\n"
            " *   Offsets indizieren es deshalb direkt.\n"
            " * Steuer-Ops: 01=END 02=YesNo-Branch(2 Operanden) 03=Seitenumbruch/YesNo\n"
            " *   05=Farbe 06=Item-Namen einsetzen 08=Zeilenumbruch; 0x00=Leerzeichen. */\n"
            % (NIDS, NIDS, NIDS - 1, NSCR))
    f.write("#define RE15_ITEM_PROMPT_NIDS %d\n" % NIDS)
    f.write("#define RE15_ITEM_PROMPT_NSCRIPTS %d\n" % NSCR)
    f.write("static const unsigned short re15_item_prompt_name_off[%d] = {%s};\n"
            % (NIDS, ",".join("0x%x" % o for o in offs)))
    f.write("static const unsigned char re15_item_prompt_name_blob[%d] = {%s};\n"
            % (len(name_blob), carr(name_blob)))
    f.write("static const unsigned short re15_item_prompt_script_off[%d] = {%s};\n"
            % (NSCR, ",".join("0x%x" % o for o in soffs)))
    f.write("static const unsigned char re15_item_prompt_script_blob[%d] = {%s};\n"
            % (len(scr_blob), carr(scr_blob)))

print("wrote %s: %d Namen (Blob %d B), %d Skripte (Blob %d B)"
      % (OUT, NIDS, len(name_blob), NSCR, len(scr_blob)))
