#!/usr/bin/env python3
"""Generate engine/src/gen/mc_title_bank.inc -- die byte-true Datenbasis des BIOS-
Memory-Card-Blocktitels (FUN_80026e54).

Quelle: info/Re1.5/PSX.EXE (MZD-Build, md5 b55fdaa5b9ec0f84bdd8a6b1107ea0b0,
t_addr 0x80010000; Datei-Offset = RAM - 0x80010000 + 0x800). PSX.EXE liegt bewusst
NICHT in shared_assets (Single-Asset-Root gilt fuer Spiel-Assets) — deshalb wird
diese Tabelle wie gen_inv_name_bank.inc zur Build-Zeit vendored und committet.

Belege (analysis/bug_save_room_name_recheck.md §2.2 / save_system_patched_build.md §3.2,
Bytes in dieser Session erneut selbst gelesen):
  - Leon-Template  DAT_800107f8 (Datei 0x00ff8, 0x2a B):  "ＢＩＯ　ＨＡＺＡＲＤ　「Ｌｅｏｎ　／００／"
  - Elza-Template  DAT_800107cc (Datei 0x00fcc, 0x2a B):  "…「Ｅｌｚａ　／００／"
    (memcpy 0x2a @0x80026e98/9c; Charakter-Weiche lbu 0x800B0FBE @0x80026e58,
     bit0==0 -> Leon @0x80026e94, sonst Elza @0x80026e80)
  - Ziffern: Template[+0x25] += n/10, Template[+0x27] += n%10 (sb v1,37(s0) @0x80026ec8,
    sb v0,39(s0) @0x80026f00; Basis = low byte der Vollbreiten-０ 0x82 4F — Datei-Bytes
    an +0x24..0x27 sind 82 4f 82 4f, selbst verifiziert)
  - Ortsname: memcpy(dst+0x2a, 0x80073628 + 0x13*idx, 0x13) (@0x80026f0c-2c);
    SJIS-Tabelle @0x80073628 = Datei 0x63e28, Stride 0x13, EXAKT 7 Eintraege
    (Eintrag 7 = Fremddaten "bu00:"). Inhaltlich RE1-Herrenhaus-Leftovers.
"""
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")
SRC = os.path.join(ROOT, "..", "info", "Re1.5", "PSX.EXE")
OUT = os.path.join(ROOT, "engine", "src", "gen", "mc_title_bank.inc")

LEON = 0x00FF8      # DAT_800107f8
ELZA = 0x00FCC      # DAT_800107cc
TMPL_LEN = 0x2A     # memcpy-Laenge @0x80026e9c (ori a2,zero,0x2a)
SJIS = 0x63E28      # 0x80073628
SJIS_STRIDE = 0x13  # @0x80026f0c-18 (*19) + memcpy 0x13 @0x80026f2c
SJIS_COUNT = 7      # Eintrag [7] beginnt mit 00 00 00 'bu00:' -> Fremddaten

def carray(name, data, note):
    lines = [f"/* {note} */", f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i+12]) + ",")
    lines.append("};")
    return "\n".join(lines)

def main():
    with open(SRC, "rb") as f:
        d = f.read()
    leon = d[LEON:LEON+TMPL_LEN]
    elza = d[ELZA:ELZA+TMPL_LEN]
    sjis = d[SJIS:SJIS+SJIS_STRIDE*SJIS_COUNT]
    assert leon[0x24:0x28] == b"\x82\x4f\x82\x4f", "Ziffern-Anker (00) fehlt im Leon-Template"
    assert elza[0x24:0x28] == b"\x82\x4f\x82\x4f", "Ziffern-Anker (00) fehlt im Elza-Template"
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", newline="\n") as f:
        f.write("/* AUTO-GENERATED by tools/gen_mc_title_bank.py -- DO NOT EDIT.\n"
                " * Quelle: info/Re1.5/PSX.EXE (Offsets im Generator-Header belegt). */\n\n")
        f.write(carray("s_mc_tmpl_leon", leon,
                       "DAT_800107f8 (Datei 0xff8, 0x2a B) -- BIO HAZARD-Leon-Template, memcpy @0x80026e98") + "\n\n")
        f.write(carray("s_mc_tmpl_elza", elza,
                       "DAT_800107cc (Datei 0xfcc, 0x2a B) -- Elza-Template, Weiche @0x80026e74-80") + "\n\n")
        f.write(carray("s_mc_sjis_loc", sjis,
                       "SJIS-Ortsnamen @0x80073628 (Datei 0x63e28), Stride 0x13, 7 Eintraege -- Anhang @0x80026f28") + "\n")
    print(f"wrote {OUT}: leon/elza {TMPL_LEN} B, sjis {SJIS_STRIDE}x{SJIS_COUNT} B")

if __name__ == "__main__":
    main()
